"Filed out from Dolphin Smalltalk 2002 release 5.00"!

AboraTests subclass: #AboraFeUiTests
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
AboraFeUiTests guid: (GUID fromString: '{50BE1B6F-06A1-405A-9887-9E47D0C746A5}')!
AboraFeUiTests comment: ''!
!AboraFeUiTests categoriesForClass!SUnit! !
!AboraFeUiTests class methodsFor!

isAbstract
	"Override to true if a TestCase subclass is Abstract and should not have
	TestCase instances built from it"

	^self name = #AboraFeUiTests! !
!AboraFeUiTests class categoriesFor: #isAbstract!public! !

