"Filed out from Dolphin Smalltalk 2002 release 5.00"!

FeConnection subclass: #FeDirectConnection
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
FeDirectConnection guid: (GUID fromString: '{CF3E7C0D-8699-428F-83E3-7CDBDCF44DD1}')!
FeDirectConnection comment: ''!
!FeDirectConnection categoriesForClass!Kernel-Objects! !
!FeDirectConnection methodsFor!

sendAndReceive: message
	^message value! !
!FeDirectConnection categoriesFor: #sendAndReceive:!public! !

