"Filed out from Dolphin Smalltalk 2002 release 5.00"!

AboraError subclass: #AboraNotAuthorizedError
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
AboraNotAuthorizedError guid: (GUID fromString: '{4BC50C37-60EA-435B-870E-7FDC1B6511B2}')!
AboraNotAuthorizedError comment: ''!
!AboraNotAuthorizedError categoriesForClass!Kernel-Exception Handling! !
