"Filed out from Dolphin Smalltalk 2002 release 5.00"!

BeWork subclass: #BeClub
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
BeClub guid: (GUID fromString: '{0C7AA34A-9FFC-4E31-B2E1-B8DB747E5828}')!
BeClub comment: ''!
!BeClub categoriesForClass!Kernel-Objects! !
!BeClub methodsFor!

makeFeProxy
	^FeContentElementProxy forId: self id class: #FeClub
! !
!BeClub categoriesFor: #makeFeProxy!private! !

