"Filed out from Dolphin Smalltalk 2002 release 5.00"!

AboraObject subclass: #Thunk
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
Thunk guid: (GUID fromString: '{4FDDA3E6-DEF0-4EF1-8B94-5FB6517CB50D}')!
Thunk comment: ''!
!Thunk categoriesForClass!Kernel-Objects! !
!Thunk methodsFor!

value
	self subclassResponsibility! !
!Thunk categoriesFor: #value!public! !

